@ProductApi_HostAddress = http://localhost:5105

###
GET {{ProductApi_HostAddress}}/products/
Accept: application/json

###
GET {{ProductApi_HostAddress}}/products/1
Accept: application/json

###
POST {{ProductApi_HostAddress}}/products
Accept: application/json
Content-Type: application/json

{
  "name": "Sample Product",
  "brand": "Sample Brand",
  "price":  19.99
}

###
PUT {{ProductApi_HostAddress}}/products/1
Accept: application/json
Content-Type: application/json

{
  "name": "Sample Product NEW!",
  "brand": "Sample Brand",
  "price":  20.00
}

###
DELETE {{ProductApi_HostAddress}}/products/1
Accept: application/json